import { test, expect } from '@playwright/test';

export function registerRegexUiTest() {
  test('预设自动读取正则、手动新增、保存恢复、提取其他预设及导出',async({page})=>{
    await page.goto('./');
    await page.getByRole('button',{name:'写作预设',exact:true}).click();
    const file=(name:string,data:unknown)=>({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
    const embedded={scriptName:'预设内置规则',findRegex:'/旧词/g',replaceString:'新词',placement:[2],promptOnly:true};
    await page.getByLabel('导入预设 JSON',{exact:true}).setInputFiles(file('正则测试.json',{prompts:[{identifier:'main',content:'测试'}],extensions:{regex_scripts:[embedded]}}));
    await expect(page.getByRole('status')).toContainText('自动读取 1 条正则');
    await page.getByRole('tab',{name:'正则',exact:false}).click();
    const editor=page.getByRole('region',{name:'正则管理'});
    await expect(editor.getByLabel('脚本名称')).toHaveValue('预设内置规则');
    await editor.getByRole('button',{name:'添加正则',exact:true}).click();
    await editor.getByLabel('脚本名称').fill('手动规则');
    await editor.getByLabel('查找表达式',{exact:true}).fill('/测试/g');
    await editor.getByLabel('替换内容',{exact:true}).fill('替换结果');
    await page.getByRole('tab',{name:'参数',exact:true}).click();
    await page.getByLabel('最大输出 tokens（留空使用供应商默认值）',{exact:true}).fill('8192');
    await page.getByRole('button',{name:'保存预设',exact:true}).click();
    await expect(page.getByRole('status')).toContainText('已保存');
    await page.reload();
    await page.getByRole('button',{name:'写作预设',exact:true}).click();
    await page.getByLabel('管理预设',{exact:true}).selectOption({label:'正则测试'});
    await page.getByRole('tab',{name:'正则',exact:false}).click();
    await editor.getByRole('button',{name:/手动规则/}).click();
    await expect(editor.getByLabel('脚本名称')).toHaveValue('手动规则');
    await expect(editor.getByLabel('替换内容',{exact:true})).toHaveValue('替换结果');
    await page.getByRole('tab',{name:'参数',exact:true}).click();
    await expect(page.getByLabel('最大输出 tokens（留空使用供应商默认值）',{exact:true})).toHaveValue('8192');
    await page.getByRole('tab',{name:'正则',exact:false}).click();
    await page.getByLabel('导入正则 JSON',{exact:true}).setInputFiles(file('其他预设.json',{prompts:[{identifier:'notImported',content:'不要导入该提示词'}],extensions:{extensions:{regex_scripts:[{...embedded,scriptName:'提取的规则'}]}}}));
    await expect(page.getByRole('status')).toContainText('已读取并保存 1 条正则');
    await expect(editor.getByRole('button',{name:/提取的规则/})).toBeVisible();
    await expect(editor.locator('.editor-list-row')).toHaveCount(3);
    await expect(page.getByLabel('预设名称',{exact:true})).toHaveValue('正则测试');
    await editor.getByRole('button',{name:/手动规则/}).click();
    await editor.getByText('测试当前规则',{exact:true}).click();
    await editor.getByLabel('测试文本',{exact:true}).fill('测试内容');
    await editor.getByRole('button',{name:'运行测试',exact:true}).click();
    await expect(editor.locator('.regex-test-result')).toContainText('替换结果内容');
    await page.locator('.modal').evaluate(el=>el.scrollTop=0);
    await editor.locator('.editor-detail').evaluate(el=>el.scrollTop=0);
    await page.screenshot({path:'test-results/preset-regex-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.locator('.modal').evaluate(el=>el.scrollTop=0);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
    await page.screenshot({path:'test-results/preset-regex-mobile.png',fullPage:true});
    const downloadPromise=page.waitForEvent('download');
    await editor.getByRole('button',{name:'导出正则 JSON',exact:true}).click();
    const download=await downloadPromise;expect(download.suggestedFilename()).toBe('regex-scripts.json');
    const stream=await download.createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();
    expect(JSON.parse(text).map((s:{scriptName:string})=>s.scriptName)).toEqual(['预设内置规则','手动规则','提取的规则']);
    await editor.getByRole('button',{name:'删除当前正则',exact:true}).click();
    await expect(editor.locator('.editor-list-row')).toHaveCount(2);
    await expect(editor.getByLabel('脚本名称')).toHaveValue('提取的规则');
    await page.getByRole('button',{name:'保存预设',exact:true}).click();
    await expect(page.getByRole('status')).toContainText('已保存');
    await page.reload();await page.getByRole('button',{name:'写作预设',exact:true}).click();
    await page.getByRole('tab',{name:'正则',exact:false}).click();
    await expect(editor.locator('.editor-list-row')).toHaveCount(2);
    await expect(editor.getByRole('button',{name:/手动规则/})).toHaveCount(0);
    page.once('dialog',dialog=>dialog.dismiss());
    await editor.getByRole('button',{name:'清空全部正则',exact:true}).click();
    await expect(editor.locator('.editor-list-row')).toHaveCount(2);
    page.once('dialog',dialog=>dialog.accept());
    await editor.getByRole('button',{name:'清空全部正则',exact:true}).click();
    await expect(editor.getByRole('heading',{name:'暂无正则'})).toBeVisible();
    await page.getByRole('button',{name:'保存预设',exact:true}).click();
    await expect(page.getByRole('status')).toContainText('已保存');
    await page.reload();await page.getByRole('button',{name:'写作预设',exact:true}).click();
    await page.getByRole('tab',{name:'正则',exact:false}).click();
    await expect(editor.getByRole('heading',{name:'暂无正则'})).toBeVisible();
    const emptyExport=page.waitForEvent('download');
    await page.getByRole('button',{name:'导出已保存预设',exact:true}).click();
    const savedStream=await (await emptyExport).createReadStream();let savedText='';
    for await(const chunk of savedStream!)savedText+=chunk.toString();
    expect(JSON.parse(savedText).regexScripts).toEqual([]);
    expect(JSON.parse(savedText).extensions.regex_scripts).toEqual([]);
    await editor.getByRole('button',{name:'添加正则',exact:true}).click();
    await editor.getByRole('button',{name:'删除当前正则',exact:true}).click();
    await expect(editor.getByRole('heading',{name:'暂无正则'})).toBeVisible();
  });
}
